apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: vfw/host-device-ifname
  name: host-device-ifname
  namespace: vfw
  annotations:
    netcrd/hostdev.unprotected.private.net.ifname: "veth12"
    internal.kpt.dev/upstream-identifier: 'k8s.cni.cncf.io|NetworkAttachmentDefinition|vfw|host-device-ifname'
spec:
  config: '{ "cniVersion": "0.3.0", "type": "host-device", "device": "ifname" }'
