apiVersion: v1
kind: Service
metadata: # kpt-merge: /packetgen-service
  name: packetgen-service
  labels:
    app: pktgen-host-netdevice
    chart: pktgen-host-netdevice
    release: firewall-host-netdevice
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|packetgen-service'
  namespace: vfw
spec:
  type: NodePort
  ports:
  - port: 2831
    nodePort: 30831
  selector:
    app: pktgen-host-netdevice
    release: firewall-host-netdevice
